### ISSUE TITLE
Add ability to test within this repository

### ISSUE THREAD

**Issue by tlemburg** [unl/sitemaster_plugin_unl#20]
Instead of having to run the tests by installing the plugin and running the tests through sitemaster.

Document both of these processes

**Comment by mfairchild365** [comment]
The plugin depends on the sitemaster framework, so testing this repo without sitemaster installed won't work.

You should be able to run tests with the plugin installed via a command like `php vendor/bin/phpunit --bootstrap tests/init.php pugins/plugin_unl/tests`

This requirement isn't ideal in terms of automated testing with something like travis-ci, but it is workable. When running the tests manually, you should have sitemaster installed anyway, so I see little benefit to adding an ability to run tests without sitemaster instaleld.

Feel free to document this when making any additions

**Comment by mfairchild365** [comment]
I went ahead and added an entry to the wiki for sitemaster regarding this. https://github.com/UNLSiteMaster/site_master/wiki/Installing-SiteMaster---demo-testing-site
